import { parseBackendStatus, parseBackendTarget, parseBackendTargets, parseServerVideos, parseTargetsEnvelope, parseVideoSummary } from "./backend-parser";

const valid = { id: 4, sinif: "aircraft", guven: 1.4, hits: 8, hiz_px_s: 12.5, zigzag: -1, bbox: { x: .42, y: .2, width: .25, height: .35 }, model: "F-16", model_skor: .84, dusuk_guven: false, ulke: "ABD", uretici: "Üretici", rol: "Savaş uçağı", adaylar: [{ model: "F-16", skor: .7 }, { model: "F-16", skor: .9 }, { model: "F-15", skor: 3 }], vlm: { gercek_tahmin: "F-16", arac_sinifi: "Sabit kanat", tehdit_seviyesi: "yüksek", dogrulama: "onaylandı", hedef_modeli_tutarlilik: "tutarlı" }, llm: { summary: "Hedef değerlendirmesi", risk: "orta", actions: ["Takibi sürdür"] }, yon: "parse edilmemeli" };

describe("backend payload parser", () => {
  it("status payload ve eksik alanları güvenli parse eder", () => { expect(parseBackendStatus({ calisiyor: true, kaynak: "C:\\x.mp4", frame_no: 3 })).toEqual({ calisiyor: true, kaynak: "C:\\x.mp4", frame_no: 3, hedef_sayisi: undefined, model_sayisi: undefined }); expect(parseBackendStatus("bad")).toEqual({}); });
  it("targets envelope için array zorunlu tutar", () => { expect(parseTargetsEnvelope({ frame: 4, hedefler: [] })).toEqual({ frame: 4, hedefler: [] }); expect(parseTargetsEnvelope({ hedefler: "bad" })).toBeUndefined(); });
  it("geçerli hedefi canonical aşamalara çevirir", () => { const target = parseBackendTarget(valid, "http://localhost:8000")!; expect(target.displayName).toBe("F-16"); expect(target.detection.detail?.confidence).toBe(1); expect(target.detection.detail?.zigzagScore).toBe(0); expect(target.detection.durationMs).toBeUndefined(); expect(target.vrag.status).toBe("completed"); expect(target.vlm.status).toBe("completed"); expect(target.llm.status).toBe("completed"); });
  it("adayları model bazında birleştirip skorla sıralar ve sınırlar", () => { const candidates = parseBackendTarget(valid, "")!.vrag.detail!.candidates; expect(candidates.map((item) => [item.model, item.score])).toEqual([["F-15", 1], ["F-16", .9]]); });
  it("VLM tehdidini nihai hedef riski yapmaz, LLM riskini kullanır", () => { const target = parseBackendTarget(valid, "")!; expect(target.vlm.detail?.threatHypothesis).toBe("high"); expect(target.risk).toBe("medium"); const noLlm = parseBackendTarget({ ...valid, llm: null }, "")!; expect(noLlm.risk).toBe("unknown"); expect(noLlm.llm.status).toBe("waiting"); });
  it("düşük güven ve VLM çelişkisini warning yapar", () => { const target = parseBackendTarget({ ...valid, dusuk_guven: true, vlm: { ...valid.vlm, dogrulama: "çelişkili" } }, "")!; expect(target.vrag.status).toBe("warning"); expect(target.vlm.status).toBe("warning"); });
  it("null VLM/LLM ve boş VRAG sonucunu waiting bırakır", () => { const target = parseBackendTarget({ id: 2, sinif: "aircraft", guven: .4, vlm: null, llm: null }, "")!; expect(target.vrag.status).toBe("waiting"); expect(target.vlm.status).toBe("waiting"); expect(target.llm.status).toBe("waiting"); });
  it("ghost ve bozuk hedefi atarken geçerli hedefi korur", () => { const targets = parseBackendTargets([{ id: -1 }, { id: "bad" }, valid], ""); expect(targets.map((target) => target.id)).toEqual([4]); });
  it("yön alanını canonical hedefe taşımaz", () => { expect(JSON.stringify(parseBackendTarget(valid, ""))).not.toContain("parse edilmemeli"); });
  it("yalnız normalize ve sınırlar içindeki hedef kutusunu taşır", () => { expect(parseBackendTarget(valid, "")?.trackingBox).toEqual({ x: .42, y: .2, width: .25, height: .35 }); expect(parseBackendTarget({ ...valid, bbox: { x: .9, y: .2, width: .2, height: .2 } }, "")?.trackingBox).toBeUndefined(); });
  it("sunucu video listesini parse eder ve eksik alanlı girdileri atar", () => { expect(parseServerVideos({ videolar: [{ ad: "f15.mp4", yol: "/data/f15.mp4" }, { ad: "eksik-yol" }, { yol: "/data/eksik-ad.mp4" }, "bad"] })).toEqual([{ name: "f15.mp4", path: "/data/f15.mp4" }]); expect(parseServerVideos({})).toEqual([]); expect(parseServerVideos("bad")).toEqual([]); });
  it("video-geneli özeti FinalOutput'a çevirir, zaman etiketini saniyeye çevirir ve kritik bayrağını taşır", () => { const result = parseVideoSummary({ status: "final", summary: "Videoda bir İHA gözlemlendi.", events: [{ time: "01:05", event: "İHA tespit edildi", critical: true }, { time: "01:10", event: "Devam ediyor", critical: false }], risk: "yüksek", actions: ["Gözlem sürdürülsün"] }); expect(result.status).toBe("final"); expect(result.summary).toBe("Videoda bir İHA gözlemlendi."); expect(result.risk).toBe("high"); expect(result.events).toEqual([{ id: "video-summary-event-1", timeSeconds: 65, timeLabel: "01:05", title: "İHA tespit edildi", description: "İHA tespit edildi", risk: "high", critical: true, status: "completed" }, { id: "video-summary-event-2", timeSeconds: 70, timeLabel: "01:10", title: "Devam ediyor", description: "Devam ediyor", risk: "high", critical: false, status: "completed" }]); expect(result.actions).toEqual([{ id: "video-summary-action-1", label: "Gözlem sürdürülsün", priority: "normal" }]); });
  it("video-geneli özet eksik/bozuk gelirse pending'e düşer", () => { expect(parseVideoSummary("bad")).toEqual({ status: "pending", summary: "", events: [], risk: "unknown", actions: [] }); expect(parseVideoSummary({})).toEqual({ status: "pending", summary: "", events: [], risk: "unknown", actions: [] }); });
});
