import { fireEvent, render, screen } from "@testing-library/react";
import { VideoViewport } from "./VideoViewport";

describe("VideoViewport sources", () => {
  it("local preview için otomatik oynamayan ve native controls içermeyen video kullanır", () => { const { container } = render(<VideoViewport source={{ type: "local-preview", url: "blob:local", name: "test" }} />); const video = container.querySelector("video"); expect(video).toBeInTheDocument(); expect(video).not.toHaveAttribute("autoplay"); expect(video).not.toHaveAttribute("loop"); expect(video).toHaveProperty("muted", true); expect(video).toHaveAttribute("disablepictureinpicture"); expect(video).not.toHaveAttribute("controls"); expect(container.querySelector("img")).not.toBeInTheDocument(); });
  it("oturum durumunu yerel video oynatımına yansıtır", () => { const pause = vi.spyOn(HTMLMediaElement.prototype, "pause").mockImplementation(() => undefined); const play = vi.spyOn(HTMLMediaElement.prototype, "play").mockResolvedValue(); const source = { type: "local-preview" as const, url: "blob:local", name: "test" }; const { rerender } = render(<VideoViewport source={source} playbackStatus="running" />); expect(play).toHaveBeenCalled(); rerender(<VideoViewport source={source} playbackStatus="paused" />); expect(pause).toHaveBeenCalled(); play.mockClear(); rerender(<VideoViewport source={source} playbackStatus="completed" />); expect(play).toHaveBeenCalled(); vi.restoreAllMocks(); });
  it("MJPEG için img kullanır ve stream URL'sini korur", () => { const { container } = render(<VideoViewport source={{ type: "mjpeg", url: "/video?_=1", name: "Backend" }} />); expect(container.querySelector("img")).toHaveAttribute("src", "/video?_=1"); });
  it("MJPEG hatasında Türkçe hata ve kontrollü retry gösterir", () => { const { container } = render(<VideoViewport source={{ type: "mjpeg", url: "/video?_=1", name: "Backend" }} />); fireEvent.error(container.querySelector("img")!); expect(screen.getByRole("alert")).toHaveTextContent("Canlı görüntü alınamadı"); fireEvent.click(screen.getByRole("button", { name: "Yeniden Dene" })); expect(container.querySelector("img")).toBeInTheDocument(); });
  it("yerel video bittiğinde son karede kalır ve bitişi bildirir", () => { const onVideoEndedChange = vi.fn(); const { container } = render(<VideoViewport source={{ type: "local-preview", url: "blob:local", name: "test" }} onVideoEndedChange={onVideoEndedChange} />); const video = container.querySelector("video")!; video.currentTime = 12; fireEvent.ended(video); expect(video.currentTime).toBe(12); expect(onVideoEndedChange).toHaveBeenLastCalledWith(true); });
  it("yerel video zamanını dışarıya bildirir", () => { const onPlaybackTimeChange = vi.fn(); const { container } = render(<VideoViewport source={{ type: "local-preview", url: "blob:local", name: "test" }} onPlaybackTimeChange={onPlaybackTimeChange} />); const video = container.querySelector("video")!; Object.defineProperty(video, "duration", { configurable: true, value: 53 }); video.currentTime = 12; fireEvent.timeUpdate(video); expect(onPlaybackTimeChange).toHaveBeenLastCalledWith({ currentSeconds: 12, durationSeconds: 53 }); });
});
